version: "3.9"
networks:
  app-tier:
    driver: bridge
services:
  mongo:
    env_file: .env
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${POSTGRES_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-tier

  # mongo-express:
  #   env_file: .env
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${POSTGRES_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${POSTGRES_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@mongo:27017/
  #   networks:
  #     - app-tier
